/**
 * lib/cms/decor-pairs.ts
 *
 * Stub CMS helper for the Day ↔ Night Decor Switcher (docs/09 §M).
 *
 * This file will be replaced by a Payload query when the `decorPairs`
 * collection lands in Sprint 2. The shape MUST stay backwards-compatible:
 * the marketing components consume `DecorPair[]` and nothing more.
 *
 * Launch budget: 4 pairs. The section can grow to 10 once the owner
 * generates more dual-lighting compositions.
 */

export type DecorSubject =
  | "mandap"
  | "stage"
  | "haldi"
  | "mehendi"
  | "bday"
  | "anniv"
  | "entry"
  | "sangeet"
  | "reception"
  | "other";

export type DecorAspect = "1:1" | "4:5" | "3:2" | "16:9";

export type DecorPair = {
  /** Stable identifier — matches the source filename, e.g. "DECOR-MANDAP-01". */
  pairId: string;
  /** Subject category — drives caption grouping. */
  subject: DecorSubject;
  /** Short, human-readable label shown beneath / over the card. */
  caption: string;
  /** Path under /public for the DAY lighting state. */
  dayImageSrc: string;
  /** Path under /public for the NIGHT lighting state. */
  nightImageSrc: string;
  /** Tiny base64 LQIP shared by both states (composition is identical). */
  blurDataURL: string;
  /** Aspect ratio — drives the card's CSS aspect-ratio. */
  aspectRatio: DecorAspect;
  /** Display order in the switcher grid (ascending). */
  order: number;
};

/**
 * Tiny shared placeholder LQIP. Real pairs will ship per-image
 * blurDataURLs generated by Payload's upload pipeline.
 */
const PLACEHOLDER_BLUR =
  "data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAxMCAxMCI+PHJlY3Qgd2lkdGg9IjEwIiBoZWlnaHQ9IjEwIiBmaWxsPSIjMWExNzE0Ii8+PC9zdmc+";

/**
 * The four launch pairs called out in docs/09 §M.
 * Paths follow the convention in §M ("Suggested file naming convention").
 */
const LAUNCH_PAIRS: ReadonlyArray<DecorPair> = [
  {
    pairId: "DECOR-MANDAP-01",
    subject: "mandap",
    caption: "Traditional Bengali mandap",
    dayImageSrc: "/media/decor-pairs/mandap-01-day.jpg",
    nightImageSrc: "/media/decor-pairs/mandap-01-night.jpg",
    blurDataURL: PLACEHOLDER_BLUR,
    aspectRatio: "4:5",
    order: 10,
  },
  {
    pairId: "DECOR-STAGE-01",
    subject: "stage",
    caption: "Sangeet stage",
    dayImageSrc: "/media/decor-pairs/stage-01-day.jpg",
    nightImageSrc: "/media/decor-pairs/stage-01-night.jpg",
    blurDataURL: PLACEHOLDER_BLUR,
    aspectRatio: "16:9",
    order: 20,
  },
  {
    pairId: "DECOR-HALDI-01",
    subject: "haldi",
    caption: "Haldi backdrop",
    dayImageSrc: "/media/decor-pairs/haldi-01-day.jpg",
    nightImageSrc: "/media/decor-pairs/haldi-01-night.jpg",
    blurDataURL: PLACEHOLDER_BLUR,
    aspectRatio: "1:1",
    order: 30,
  },
  {
    pairId: "DECOR-BDAY-01",
    subject: "bday",
    caption: "Milestone birthday setup",
    dayImageSrc: "/media/decor-pairs/bday-01-day.jpg",
    nightImageSrc: "/media/decor-pairs/bday-01-night.jpg",
    blurDataURL: PLACEHOLDER_BLUR,
    aspectRatio: "3:2",
    order: 40,
  },
];

/**
 * Resolve the pairs that should appear on the Home-page switcher.
 * When Payload ships, this becomes an async query honouring
 * `featuredOnHome` + sort by `order`.
 *
 * Kept sync for now so the section can stay a Server Component
 * without a Suspense boundary at the page level.
 */
export function getFeaturedDecorPairs(): ReadonlyArray<DecorPair> {
  return [...LAUNCH_PAIRS].sort((a, b) => a.order - b.order);
}

/** Map an aspect-ratio token to a CSS `aspect-ratio` value. */
export function aspectRatioToCss(aspect: DecorAspect): string {
  switch (aspect) {
    case "1:1":
      return "1 / 1";
    case "4:5":
      return "4 / 5";
    case "3:2":
      return "3 / 2";
    case "16:9":
      return "16 / 9";
  }
}
